### ISSUE TITLE
olefy crash - olefy ERROR default_exception_handler Fatal error: protocol.eof_received() call failed.

### ISSUE THREAD

**Issue by redgloboli** [HeinleinSupport/olefy#15]
Hi,

olefy doesn't work here and errors out on debian buster.

on one system i get (not scanning):

Dec 08 08:27:12 debian python3[11842]: olefy ERROR default_exception_handler Fatal error: protocol.eof_received() call failed.
Dec 08 08:27:12 debian python3[11842]: protocol: <__main__.AIO object at 0x7f2d52a8a2e8>
Dec 08 08:27:12 debian python3[11842]: transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Dec 08 08:27:12 debian python3[11842]: Traceback (most recent call last):
Dec 08 08:27:12 debian python3[11842]:   File "/usr/lib/python3.7/asyncio/selector_events.py", line 823, in _read_ready__on_eof
Dec 08 08:27:12 debian python3[11842]:     keep_open = self._protocol.eof_received()
Dec 08 08:27:12 debian python3[11842]:   File "/opt/olefy/olefy.py", line 171, in eof_received
Dec 08 08:27:12 debian python3[11842]:     rspamd_id = olefy_headers['Rspamd-ID'][:6] or ''
Dec 08 08:27:12 debian python3[11842]: KeyError: 'Rspamd-ID'

on the other system i get (scanning):

Dez 08 08:26:44 debian2 python3[13290]: olefy DEBUG data_received ('127.0.0.1', 57130) data received from new connection
Dez 08 08:26:44 debian2 python3[13290]: olefy ERROR default_exception_handler Fatal error: protocol.eof_received() call failed.
Dez 08 08:26:44 debian2 python3[13290]: protocol: <__main__.AIO object at 0x7f2bcfa980b8>
Dez 08 08:26:44 debian2 python3[13290]: transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Dez 08 08:26:44 debian2 python3[13290]: Traceback (most recent call last):
Dez 08 08:26:44 debian2 python3[13290]:   File "/usr/lib/python3.7/asyncio/selector_events.py", line 823, in_read_ready__on_eof
Dez 08 08:26:44 debian2 python3[13290]:     keep_open = self._protocol.eof_received()
Dez 08 08:26:44 debian2 python3[13290]:   File "/opt/olefy/olefy.py", line 171, in eof_received
Dez 08 08:26:44 debian2 python3[13290]:     rspamd_id = olefy_headers['Rspamd-ID'][:6] or ''
Dez 08 08:26:44 debian2 python3[13290]: KeyError: 'Rspamd-ID'

**Comment by redgloboli** [comment]
ok, i just overlooked this one - https://github.com/HeinleinSupport/olefy/pull/14/commits

error is gone, still no scanning, i need have a better look now.
